
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Mar 22 16:06:46 COT 2022
//----------------------------------------------------

package analizadorSintactico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Punto = 4;
  public static final int Mayuscula = 3;
  public static final int VACIO = 2;
  public static final int ERROR = 8;
  public static final int MAYUSCULA = 5;
  public static final int EOF = 0;
  public static final int Coma = 10;
  public static final int Punto_coma = 7;
  public static final int error = 1;
  public static final int Minuscula = 6;
  public static final int Dos_puntos = 11;
  public static final int Comillas = 9;
}

