
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Mar 22 11:19:09 COT 2022
//----------------------------------------------------

package semanticopf;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Punto_y_coma = 3;
  public static final int Palabracun = 15;
  public static final int Parentesis_c = 8;
  public static final int Palabramp = 28;
  public static final int Parentesis_a = 7;
  public static final int Numero = 11;
  public static final int Mayuscula = 30;
  public static final int PalabraMB = 24;
  public static final int Palabra = 16;
  public static final int PalabraNP = 22;
  public static final int Corchete_c = 10;
  public static final int ERROR = 31;
  public static final int Corchete_a = 9;
  public static final int Palabraion = 18;
  public static final int Comillas = 2;
  public static final int Palabramb = 25;
  public static final int PalabraION = 17;
  public static final int Coma = 5;
  public static final int Palabranp = 23;
  public static final int Palabracion = 20;
  public static final int PalabraNB = 26;
  public static final int PalabracION = 19;
  public static final int EOF = 0;
  public static final int PalabraUN = 12;
  public static final int error = 1;
  public static final int Palabranb = 27;
  public static final int Punto = 6;
  public static final int Dos_puntos = 4;
  public static final int PalabracUN = 14;
  public static final int Palabraun = 13;
  public static final int Palabra2 = 29;
  public static final int PalabraMP = 21;
}

